- name: apache2 package is present
  apt:
    name: apache2
    state: latest

- name: apache2 package is present
  service:
    name: apache2
    state: started

- name: quiz-roles file is installed
  template:
    src: quiz-roles.conf.j2
    dest: /etc/apache2/sites-available/quiz-roles.conf
    owner: root
    group: root
    mode: 0644

- name: Enable quiz-roles
  command: a2ensite quiz-roles.conf
  notify:
    - restart apache2

- name: disable default
  command: a2dissite 000-default.conf
  notify:
    - restart apache2

- name: HTML content is installed
  copy:
    src: html-quiz/
    dest: "/var/www/quiz-roles/{{ ansible_user }}"
